### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by robinwhittleton** [andytinkham/frederik-pohl_c-m-kornbluth_search-the-sky#1]
general
- `clean` makes a couple of changes we should accept
- `typogrify` suggests a bunch of changes. The ones that we should definitely accept are removing word joining characters after em dashes. We don’t mind if a line breaks after an em dash, we just don’t want it breaking before.
- there’s a lot of two-em dashes (⸺) used throughout the book. We’d reserve these for elision, and switch them for single em-dashes instead.

content.opf
- Add `<meta property="se:subject">Fiction</meta>` as well as the science fiction one
- Longdesc uses “6”, but usually we‘d write out small numbers, so “six”
- Italicise Galaxy as it’s a magazine
- En-dashes in the longdesc should be changed for em-dashes
- Change wiki link for Kornbluth to https://en.wikipedia.org/wiki/Cyril_M._Kornbluth

chapter-3
- “four-G” needs an abbr (but doesn’t need a full stop) - see https://standardebooks.org/manual/1.7.3/single-page#8.8.7.4.2

chapter-11
- `<b>This</b> to hell will blow ye!` should be an actual emphasis, so `<strong>This</strong> to hell will blow ye!`
- In the “That’s All, Jones” blockquote I think we can follow standard cite structure for the People’s Police line: https://standardebooks.org/manual/1.7.2/single-page#8.17
- `<q>Round pillars</q>`: why a `q`? This feels like an `<em>` to me. (if so delete the `q{}` rule in the CSS)
- `“Why We Fight”` should have semantics> `“<span epub:type="se:name.publication.pamphlet">Why We Fight</span>”`

chapter-12
- First word is in caps, should be fixed to titlecase.
- If `Ph.D.` is having a hair space we should add it to `Sc.D.` as well.

colophon
- Change wiki link for Kornbluth to https://en.wikipedia.org/wiki/Cyril_M._Kornbluth

**Comment by andytinkham** [comment]
Made all changes as discussed.
